" vim: set ts=3 expandtab filetype=vim :

" first things first
set history=1000
set scrolloff=3
set grepprg=ack\ -a
set wildmenu
set wildmode=list:longest
"let perl_fold=1

" things for unicode
set encoding=utf8
"set fileencodings=ucs-bom,utf-8,windows-1252,latin1
set fileencodings=ucs-bom,utf-8,latin1,windows-1252

"set bomb    " sets BOM (byte order mark) boolean

if &term =~ "xterm"
   if has("terminfo")
      set t_Co=8
      set t_Sf=<Esc>[3%p1%dm
      set t_Sb=<Esc>[4%p1%dm
   else
      set t_Co=8
      set t_Sf=<Esc>[3%dm
      set t_Sb=<Esc>[4%dm
   endif
endif

" ignore case differences while searching
set ignorecase

"let mapleader = ","

"nmap <Space>   /
"nmap <C-Space> ?
"imap <C-F> {<CR>}<C-O>O
"
"nmap <Leader>c i# $Id<ESC>a:$<CR># $Source<ESC>a:$<CR><ESC>
"nmap <Leader>d ma:r!date<CR>"add`ai<C-R>a<ESC><ESC>kJ
"nmap <Leader>e :call PerlMathEval()<CR>
"nmap <Leader>f oimport pdb; pdb.set_trace()<ESC>
"nmap <Leader>h :let @/ = "" <CR>
"nmap <Leader>i i i18n:translate=""<ESC>
"nmap <Leader>j :call FindUntranslated()<CR>
"nmap <Leader>o i tal:omit-tag=""<ESC>
"nmap <Leader>p i<CR>=pod<CR><CR>=head1 NAME<CR><CR>=head1 SYNOPSIS<CR><CR>=head1 DESCRIPTION<CR><CR>=cut<CR><ESC>
"nmap <Leader>s iuse strict;<CR>use warnings;<CR><ESC>
"vmap <Leader>t !perltidy
"nmap <Leader>S :call MakeSubScript()<CR>
"nmap <Leader>hc i2975 Lone Oak Drive, Suite 180<CR>Eagan, MN 55121-1553<CR><ESC>

"vmap \s :call MakeSubScript()<CR>
"

"map <F2> :echo 'Current time = ' . strftime('%c')<CR>

" handy function to evaluate perl expressions
function! PerlMathEval()
perl << EOF
    $lnum = ($curwin->Cursor)[0];
    $line = $curbuf->Get($lnum);
    $line =~ s/.*=//;
    $curbuf->Append($lnum, eval $line);
EOF
endfunction


" handy function to evaluate perl expressions
function! MakeSubScript()
perl << EOF
    $lnum = ($curwin->Cursor)[0];
    $curbuf->Append($lnum, "₁");
EOF
endfunction


function! FindUntranslated()
   let curfile = bufname("%")
   let tmpfile = tempname()
   silent execute "write! " . tmpfile
   let output = system("i18ndude find-untranslated " . tmpfile . " 2>&1")
   if output != ''
      " Make sure the output specifies the correct filename
      let output = substitute(output, fnameescape(tmpfile), fnameescape(curfile), "g")
      echo output
   endif
endfunction

" map ^N to set no-highlight-search; see http://vim.wikia.com/wiki/VimTip93
nmap <silent> <C-N> :silent noh<CR>

" see Vim Tip #1066: Quickly adding and deleting empty lines
" http://vim.sourceforge.net/tips/tip.php?tip_id=1066
noremap <silent><C-k> mz:silent +g/\m^\s*$/d<CR>`z:noh<CR>


set background=dark
set incsearch
" set hlsearch
colorscheme elflord
syntax enable
syntax sync fromstart

set whichwrap=<,>,h,l,[,]

" turn on highlighting of trailing spaces
set list
set listchars=trail:-,tab:\.\


" set folding to use file syntax
set foldmethod=syntax

filetype on                " enables filetype detection
filetype plugin on         " enables filetype-specific plugins

au BufRead,BufNewFile *.cfg         set filetype=dosini
au BufRead,BufNewFile *.js          set filetype=javascript
au BufRead,BufNewFile Makefile      set filetype=make
au BufRead,BufNewFile autohandler   set filetype=mason
au BufRead,BufNewFile dhandler      set filetype=mason
au BufRead,BufNewFile *.ma          set filetype=mason
au BufRead,BufNewFile *.mas         set filetype=mason
au BufRead,BufNewFile *.html        set filetype=mason
au BufRead,BufNewFile *.htm         set filetype=mason
au BufRead,BufNewFile *.json        set filetype=json
au BufRead,BufNewFile *.pt          set filetype=xml
au BufRead,BufNewFile *.py          set filetype=python
au BufRead,BufNewFile *.R           set filetype=R
au BufRead,BufNewFile *.t           set filetype=perl
au BufRead,BufNewFile *.sh          set filetype=shell
au BufRead,BufNewFile *rc           set filetype=rc
au BufRead,BufNewFile *.sql         set filetype=sql
au BufRead,BufNewFile *.tt          set filetype=tt2
au BufRead,BufNewFile *.tt2         set filetype=tt2
au BufRead,BufNewFile *.txt         set filetype=text
au BufRead,BufNewFile *.yaml        set filetype=yaml
au BufRead,BufNewFile *.zcml        set filetype=xml
au BufRead,BufNewFile README*       set filetype=text
au BufRead,BufNewFile Changes*      set filetype=text
au BufRead,BufNewFile version.txt   set filetype=plonever
au BufRead,BufNewFile *.djt         set filetype=htmldjango
au BufRead,BufNewFile *.css.dtml    set filetype=css

au BufNewFile,BufRead *.R           setf r
au BufNewFile,BufRead *.R           set syntax=r
au BufNewFile,BufRead *.t           set tw=200

autocmd BufNewFile *.html    0read ~/.vim/template.ma
autocmd BufNewFile *.ma      0read ~/.vim/template.ma
autocmd BufNewFile makefile  0read ~/.vim/template.make
autocmd BufNewFile Makefile  0read ~/.vim/template.make
autocmd BufNewFile *.mas     0read ~/.vim/template.ma
autocmd BufNewFile *.pl      0read ~/.vim/template.pl
autocmd BufNewFile *.pm      0read ~/.vim/template.pm
autocmd BufNewFile *.py      0read ~/.vim/template.py
autocmd BufNewFile README*   0read ~/.vim/template.README
autocmd BufNewFile *.R       0read ~/.vim/template.R
autocmd BufNewFile *.sql     0read ~/.vim/template.sql
autocmd BufNewFile *.t       0read ~/.vim/template.t
autocmd BufNewFile *.txt     0read ~/.vim/template.txt

autocmd BufWritePre *.cfg   :%s/\s\+$//e
autocmd BufWritePre *.php   :%s/\s\+$//e
autocmd BufWritePre *.py    :%s/\s\+$//e
autocmd BufWritePre *.pm    :%s/\s\+$//e
autocmd BufWritePre *.pl    :%s/\s\+$//e
autocmd BufWritePre *.pt    :%s/\s\+$//e
autocmd BufWritePre *.scm   :%s/\s\+$//e
autocmd BufWritePre *.sql   :%s/\s\+$//e
autocmd BufWritePre *.t     :%s/\s\+$//e
autocmd BufWritePre *.tt2   :%s/\s\+$//e
autocmd BufWritePre *.txt   :%s/\s\+$//e
autocmd BufWritePre *.zcml  :%s/\s\+$//e
autocmd BufWritePre .vimrc  :%s/\s\+$//e

autocmd FileType cpp          set ai et ts=4 tw=78
autocmd FileType css          set ai et ts=4
autocmd FileType dosini       set ai et ts=4
autocmd FileType javascript   set ai et ts=4
autocmd FileType json         set ai et ts=3
autocmd FileType perl         set ai et ts=4 tw=78
autocmd FileType pod          set ai et ts=4 tw=78
autocmd FileType php          set ai et ts=4 foldmethod=marker
autocmd FileType mason        set ai et ts=4
autocmd FileType make         set ts=4
autocmd FileType python       set ai et ts=4 tw=78
autocmd FileType rc           set ai et ts=4
autocmd FileType R            set ai et ts=4 tw=75
autocmd FileType scheme       set ai et ts=3 tw=78 lisp
autocmd FileType shell        set ai et ts=4
autocmd FileType sql          set ai et ts=4 tw=75
autocmd FileType text         set ai et ts=3 tw=75 foldmethod=marker
autocmd FileType tt2          set ai et ts=3 tw=65
autocmd FileType yaml         set ai et ts=2 tw=75

autocmd FileType html         set ai et ts=2 foldmethod=marker tw=78
autocmd FileType xhtml        set ai et ts=2 foldmethod=marker
autocmd FileType xml          set ai et ts=2 foldmethod=marker tw=999
autocmd FileType htmldjango   set ai et ts=2 foldmethod=marker tw=78

autocmd FileType plonever     set binary noeol




map ,f :call MakeSubScript()<CR>
